[package]
name = "mobile"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { workspace = true, features = ["router"] }
lib_ui = { workspace = true }

[features]
default = ["mobile"]
mobile = ["dioxus/mobile"]

